// This file is auto-generated by the router plugin.
// It intentionally imports from router.ts, creating a cycle.
import type { router } from './router';

export const routeTree = {
  routerType: {} as typeof router,
  routes: ['/home', '/about'],
};
