/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { Route as IndexImport } from './routes/index';
import { Route as AboutImport } from './routes/about';

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
});

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
});

export const routeTree = rootRoute.addChildren([IndexRoute, AboutRoute]);
